
package com.pdks.webService.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Mon Dec 09 20:53:59 EET 2024
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "saveCihaz", namespace = "http://webService.pdks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saveCihaz", namespace = "http://webService.pdks.com/")

public class SaveCihaz {

    @XmlElement(name = "cihazlar")
    private java.util.List<org.pdks.kgs.model.Cihaz> cihazlar;

    public java.util.List<org.pdks.kgs.model.Cihaz> getCihazlar() {
        return this.cihazlar;
    }

    public void setCihazlar(java.util.List<org.pdks.kgs.model.Cihaz> newCihazlar)  {
        this.cihazlar = newCihazlar;
    }

}

