
package com.pdks.webService.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Mon Dec 09 20:53:59 EET 2024
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "saveCihazGecisResponse", namespace = "http://webService.pdks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saveCihazGecisResponse", namespace = "http://webService.pdks.com/")

public class SaveCihazGecisResponse {

    @XmlElement(name = "return")
    private org.pdks.kgs.model.Sonuc _return;

    public org.pdks.kgs.model.Sonuc getReturn() {
        return this._return;
    }

    public void setReturn(org.pdks.kgs.model.Sonuc new_return)  {
        this._return = new_return;
    }

}

