
package com.pdks.webService.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Mon Dec 09 20:53:59 EET 2024
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "saveCihazGecis", namespace = "http://webService.pdks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saveCihazGecis", namespace = "http://webService.pdks.com/")

public class SaveCihazGecis {

    @XmlElement(name = "gecisler")
    private java.util.List<org.pdks.kgs.model.CihazGecis> gecisler;

    public java.util.List<org.pdks.kgs.model.CihazGecis> getGecisler() {
        return this.gecisler;
    }

    public void setGecisler(java.util.List<org.pdks.kgs.model.CihazGecis> newGecisler)  {
        this.gecisler = newGecisler;
    }

}

